version: "3"

services:
  mongo:
    restart: always
    image: mongo:4.0
    container_name: mongo
    volumes:
      - ./tableapp-data:/data/db

  table-backend:
    restart: always
    image: table-backend:latest
    container_name: table-backend
    depends_on:
      - mongo
    environment:
      VIRTUAL_HOST: table.example.com # your domain to backend
      VIRTUAL_PATH: /api/
      VIRTUAL_PORT: 4898 # default backend port

  table-client:
    restart: always
    image: table-client:dev
    container_name: table-client
    environment:
      VIRTUAL_HOST: table.example.com # your domain to frontend
      VIRTUAL_PATH: /
      VIRTUAL_PORT: 80 # default frontend port

  nginx-proxy:
    restart: always
    # as of 2021-10-20 path based routing is only supported for the "dev"-images
    # see: https://github.com/nginx-proxy/nginx-proxy/pull/1607 
    image: nginxproxy/nginx-proxy:dev
    container_name: nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
